version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "benchmarks/"
    schedule:
      interval: "daily"
  - package-ecosystem: "bundler"
    directory: "site/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "benchmarks/"
    schedule:
      interval: "daily"
  - package-ecosystem: "cargo"
    directory: "lib/rust/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "lib/"
    schedule:
      interval: "daily"