name: Binary Search (x5)
description: >
  Binary Search is a search algorithm that finds the position of a target value within a sorted array.
  Performs a binary search through 25 sorted integers for the third, ninth, 13th, 16th, and 21st elements.
measure: NANOSECONDS
output: MICROSECONDS
tags:
  - "number"
  - "search"