name: Report a Bug
description: Report a Bug.
labels: ['unconfirmed bug']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report a bug. Please take time to fill out the information below.
  - type: dropdown
    attributes:
      label: Bug Type
      description: What type of bug are you trying to report?
      multiple: true
      options:
        - Website Typo
        - Navigation Error
        - UI/UX Issue
        - Benchmark Inaccuracy
        - Other Unexpected Behavior
    validations:
      required: true

  - type: textarea
    attributes:
      label: Description
      placeholder: |
        Ex: "Typo in the website footer"
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Explain how to recreate or find this bug.
      placeholder: |
        Ex: 
        1. Navigate to the homepage
        2. Scroll to the bottom of the page
        3. Observe the typo in the footer
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expect the plugin to do.
      placeholder: |
        Ex: "The text should be 'Copyright 2024'"
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: What does the plugin do? What are the error messages shown?
      placeholder: |
        Ex: "The text is 'Copywrite 2024'"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        In the box below, you can attach any relevant info or files that may help us solve the bug.
        If you think this issue is relevant to any other issues, please mention it here.
  - type: textarea
    attributes:
      label: Additional Info
      description: Any additional info that may help us solve the bug.
      placeholder: |
        Ex: "I am on Firefox 100.0.0 on Windows 10"
    validations:
      required: false