name: Base64 Encode (x3)
description: >
  Base64 is an encoding scheme used to encode binary data in an ASCII format.
  This benchmark measures the time taken to encode three strings to Base64:
  "Hello, World!", "The quick brown fox jumps over the lazy dog", and "AaBbCcDdEeFf123456_!@#&*^()$=+-".
measure: NANOSECONDS
output: MICROSECONDS
tags:
  - "string"
  - "compression"
  - "algorithm"