name: SHA-256 Hashing (x25)
description: >
  Secure Hash Algorithm 2 (SHA-2) is a family of widely used cryptographic hash functions. SHA-256, its most popular variant, produces a 256-bit (32-byte) hash value.
  It is commonly used to verify the integrity of data.
  This benchmark measures the time taken to hash 25 strings using the SHA-256 algorithm.
measure: NANOSECONDS
output: MICROSECONDS
tags:
  - "string"
  - "encryption"