name: Powers of Two
description: Programs that iterate through powers of two up to 2^30, through repeated multiplication.
measure: NANOSECONDS
output: NANOSECONDS
tags:
  - "number"
  - "math"
  - "exponentiation"