- language: Python
  id: python
  file-name: main.py
  color: "3572a5"
  run: python main.py
  version: python --version
- language: JavaScript (Node)
  id: js-node
  file-name: main.cjs
  color: "f1e05a"
  run: node main.cjs
  version: node --version
- language: JavaScript (Deno)
  id: js-deno
  file-name: main.cjs
  color: "70ffaf"
  run: deno run -A main.cjs
  version: deno --version
- language: JavaScript (Bun)
  id: js-bun
  file-name: main.cjs
  color: "5d5986"
  run: bun run main.cjs
  version: bun --version
- language: Java
  id: java
  file-name: Main.java
  color: "b07219"
  run: java Main.java -Xint
  version: java --version
- language: Kotlin (JVM)
  id: kotlin-jvm
  file-name: main.kt
  color: "5f3bbe"
  location: KOTLIN_HOME
  compile: kotlinc main.kt -include-runtime -d main.kt.jar
  libraries:
    include-run: true
    main: main.kt.jar
    flag: "-cp "
    escape-paths: true
    suffix: jar
    default: kotlin/jvm
  run: kotlin -Xint MainKt
  cleanup:
    - main.kt.jar
  version: kotlinc -version
- language: Kotlin (Native)
  file: true
  id: kotlin-native
  file-name: main.kt
  color: "92316e"
  location: KOTLIN_NATIVE_HOME
  compile: kotlinc-native main.kt -o main.kt -g
  libraries:
    flag: "-l "
    escape-paths: false
    repeat: true
    suffix: klib
    windows: kotlin/windows
    mac: kotlin/mac
    linux: kotlin/linux
  run: main.kt
  cleanup:
    - main.kt.exe
    - main.kt.kexe
  version: kotlinc-native -version
- language: C++ (G++)
  file: true
  id: cpp-gnu
  file-name: main.cpp
  color: "004283"
  compile: g++ main.cpp -o main.cpp.gnu.o -std=c++17 -O0
  compile-extra:
    windows: "-lws2_32"
  run: main.cpp.gnu.o
  cleanup:
    - main.cpp.gnu.o
  version: g++ --version
- language: C++ (Clang++)
  file: true
  id: cpp-llvm
  file-name: main.cpp
  color: "006183"
  compile: clang++ main.cpp -o main.cpp.llvm.o -std=c++17 -w -O0
  run: main.cpp.llvm.o
  cleanup:
    - main.cpp.llvm.o
  version: clang++ --version
- language: C (GCC)
  file: true
  id: c-gnu
  file-name: main.c
  color: "555555"
  compile: gcc main.c ../../lib/c/nanotime/nanotime.c ../../lib/c/base64/base64.c -o main.c.gnu.o -w -O0
  compile-extra:
    windows: "-lws2_32"
    linux: "-lm"
  run: main.c.gnu.o
  cleanup:
    - main.c.gnu.o
  version: gcc --version
- language: C (Clang)
  file: true
  id: c-llvm
  file-name: main.c
  color: "888888"
  compile: clang main.c ../../lib/c/nanotime/nanotime.c ../../lib/c/base64/base64.c -o main.c.llvm.o -w -O0
  compile-extra:
    linux: "-lm"
  run: main.c.llvm.o
  cleanup:
    - main.c.llvm.o
  version: clang --version
- language: Ruby
  id: ruby
  file-name: main.rb
  color: "701516"
  run: ruby main.rb
  version: ruby --version
- language: Go
  file: true
  id: go
  file-name: main.go
  color: "375eab"
  compile: go build -o main.go.o -gcflags -N main.go
  run: main.go.o
  cleanup:
    - main.go.o
  version: go version
- language: PHP
  id: php
  file-name: main.php
  color: "777bb3"
  run: php main.php
  version: php --version
- language: Rust
  file: true
  id: rust
  file-name: main.rs
  color: "dea584"
  compile: rustc main.rs -o main.rs.o
  run: main.rs.o
  cleanup:
    - main.rs.o
    - main.rs.pdb
  version: rustc --version --verbose