- language: Python
  id: python
  color: "3572a5"
  run: python main.py
  version: python --version
- language: JavaScript (Node)
  id: js-node
  color: "f1e05a"
  run: node main.cjs
  version: node --version
- language: JavaScript (Deno)
  id: js-deno
  color: "70ffaf"
  run: deno run -A main.cjs
  version: deno --version
- language: JavaScript (Bun)
  id: js-bun
  color: "5d5986"
  run: bun run main.cjs
  version: bun --version
- language: Java
  id: java
  color: "b07219"
  run: java Main.java
  version: java --version
- language: Kotlin (JVM)
  id: kotlin-jvm
  color: "5f3bbe"
  location: KOTLIN_HOME
  compile: kotlinc main.kt -include-runtime -d main.kt.jar
  run: java -jar main.kt.jar
  cleanup:
    - main.kt.jar
  version: kotlinc -version
- language: Kotlin (Native)
  file: true
  id: kotlin-native
  color: "92316e"
  location: KOTLIN_NATIVE_HOME
  compile: kotlinc-native main.kt -o main.kt
  run: main.kt
  cleanup:
    - main.kt.exe
    - main.kt.kexe
  version: kotlinc-native -version
- language: C++ (G++)
  file: true
  id: cpp-gnu
  color: "004283"
  compile: g++ main.cpp -o main.cpp.gnu.o
  compile-extra:
    windows: "-lws2_32"
  run: main.cpp.gnu.o
  cleanup:
    - main.cpp.gnu.o
  version: g++ --version
- language: C++ (Clang++)
  file: true
  id: cpp-llvm
  color: "006183"
  compile: clang++ main.cpp -o main.cpp.llvm.o -w
  run: main.cpp.llvm.o
  cleanup:
    - main.cpp.llvm.o
  version: clang++ --version
- language: C (GCC)
  file: true
  id: c-gnu
  color: "555555"
  compile: gcc main.c ../../lib/nanotime/nanotime.c -o main.c.gnu.o
  compile-extra:
    windows: "-lws2_32"
    linux: "-lm"
  run: main.c.gnu.o
  cleanup:
    - main.c.gnu.o
  version: gcc --version
- language: C (Clang)
  file: true
  id: c-llvm
  color: "888888"
  compile: clang main.c ../../lib/nanotime/nanotime.c -o main.c.llvm.o -w
  compile-extra:
    linux: "-lm"
  run: main.c.llvm.o
  cleanup:
    - main.c.llvm.o
  version: clang --version
- language: Ruby
  id: ruby
  color: "701516"
  run: ruby main.rb
  version: ruby --version
- language: Go
  file: true
  id: go
  color: "375eab"
  compile: go build -o main.go.o main.go
  run: main.go.o
  cleanup:
    - main.go.o
  version: go version
- language: PHP
  id: php
  color: "777bb3"
  run: php main.php
  version: php --version
- language: Rust
  file: true
  id: rust
  color: "dea584"
  compile: rustc main.rs -o main.rs.o
  run: main.rs.o
  cleanup:
    - main.rs.o
    - main.rs.pdb
  version: rustc --version --verbose