name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew project tasks dependencies

  benchmark:
    runs-on: ${{ matrix.os }}
    needs: setup
    timeout-minutes: 60

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: linux
            os: ubuntu-latest
          - name: macos
            os: macos-latest
          - name: windows
            os: windows-latest

    name: Benchmark on ${{ matrix.name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      # Runtimes
      - name: Install JavaScript (Node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install JavaScript (Deno)
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Install JavaScript (Bun)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Kotlin
        uses: gmitch215/setup-kotlin@main
        with:
          version: '2.0.21'
          install-native: true
      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      # Benchmarking
      - name: Create Benchmarks
        run: ./gradlew benchmark
      - name: Upload Benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks-${{ matrix.name }}
          path: benchmarks/output
          overwrite: true

  site:
    runs-on: ubuntu-latest
    needs: benchmark
    timeout-minutes: 20

    name: Site Generation
    if: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: benchmarks-*
          path: build/benchmarks
      - name: Generate Site
        run: ./gradlew site
      - name: Upload Site
        run: bash pages.sh
