name: Build Project

on:
  push:
    branches: [ master, ver/* ]
  pull_request:
    branches: [ master, ver/* ]

  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    name: Gradle Setup
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      - name: Gradle Information
        run: ./gradlew project tasks dependencies

  run:
    runs-on: ${{ matrix.os }}
    needs: setup
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    name: Benchmark on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Change Permissions
        run: chmod +x ./gradlew
      # Runtimes
      - name: Install JavaScript (Node)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install JavaScript (Bun.sh)
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install Kotlin
        uses: gmitch215/setup-kotlin@8a96147fdb16a5f1c49af748a35e88291ed1af00
        with:
          version: '2.0.21'
          install-native: true
      # Benchmarking
      - name: Create Benchmarks
        run: ./gradlew benchmark
      - name: Upload Benchmarks
        uses: actions/upload-artifact@v4
        with:
          name: benchmarks
          path: benchmarks/output
          overwrite: true